name: jenkins
home: https://jenkins.io/
icon: https://jenkins.io/images/logos/jenkins/jenkins.png
version: 0.0.1
appVersion: 2.140
description: The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.
keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- jenkins
sources:
- <TODO: Put your link to the git repo here>
maintainers:
- name: <TODO: Put your name here>
  email: <TODO: Put your email here>
